Resources:
  PerformanceApi49E4F80B:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Body:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location:
              Fn::Sub: s3://cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}/63b49b4d6abde4fd6eeb6f13060611ff17b8a2790fba23345b554cee72cbeaf7.yml
      Name:
        Fn::Sub: ${AWS::StackName} Performance API
    Metadata:
      aws:cdk:path: performance-metrics/PerformanceApi/Resource
  PerformanceApiDeployment75666B924ab82324295f996116117b60dd274491:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: PerformanceApi49E4F80B
      Description: Automatically created by the RestApi construct
    Metadata:
      aws:cdk:path: performance-metrics/PerformanceApi/Deployment/Resource
  PerformanceApiDeploymentStageawsunknownaccountunknownregionAA2390C8:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: PerformanceApi49E4F80B
      DeploymentId:
        Ref: PerformanceApiDeployment75666B924ab82324295f996116117b60dd274491
      StageName: aws://unknown-account/unknown-region
    Metadata:
      aws:cdk:path: performance-metrics/PerformanceApi/DeploymentStage.aws:----unknown-account--unknown-region/Resource
  PerformanceApiCloudWatchRoleD7288AD5:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: performance-metrics/PerformanceApi/CloudWatchRole/Resource
  PerformanceApiAccount63D4215E:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - PerformanceApiCloudWatchRoleD7288AD5
          - Arn
    DependsOn:
      - PerformanceApi49E4F80B
    Metadata:
      aws:cdk:path: performance-metrics/PerformanceApi/Account
  PerformanceFunctionServiceRoleD339B556:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: performance-metrics/PerformanceFunction/ServiceRole/Resource
  PerformanceFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ImageUri:
          Fn::Sub: ${AWS::AccountId}.dkr.ecr.${AWS::Region}.${AWS::URLSuffix}/cdk-hnb659fds-container-assets-${AWS::AccountId}-${AWS::Region}:4c1461ddbe98f1a92345fce2cba745d4a146c3dc370134508f694dd46368f3f7
      Role:
        Fn::GetAtt:
          - PerformanceFunctionServiceRoleD339B556
          - Arn
      FunctionName: PerformanceFunction
      ImageConfig:
        Command:
          - ap.Greeter::handleRequest
      PackageType: Image
      Timeout: 900
    DependsOn:
      - PerformanceFunctionServiceRoleD339B556
    Metadata:
      aws:cdk:path: performance-metrics/PerformanceFunction/Resource
  versionCB91663C:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName:
        Ref: PerformanceFunction
    Metadata:
      aws:cdk:path: performance-metrics/version/Resource
  liveBCEC2B85:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName:
        Ref: PerformanceFunction
      FunctionVersion:
        Fn::GetAtt:
          - versionCB91663C
          - Version
      Name: live
    Metadata:
      aws:cdk:path: performance-metrics/live/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAE02Q3W7DIAyFn6X3hBbtBZa1mrTdTMqk3XvEi7wkgDCsiiLefUCbKlc+HOPPP0qqk5KnwzNcudH9eFy19SjXzwB6FC0zhiwHMoPokG30GsX5x3zE4GIQZ2s4+KhD8fb5nOgpkDVJFPDKTw0UFsuKFOBogIBXWHIrhzrXhtbRHVPlhnsBRnFBN9llRlM77V5luNrxIVqtbTQhCYJZrp2dqltiEhPM3z3I9WL1iP5tziWv0egyaPn00F/o+e5tsp0IuPKLSAK131ba0W7b5Zzs0FmmYP1SFkhJvMMfHFW+tVTq8MtEjc9j0oyyu8V/siZEM4sBAAA=
    Metadata:
      aws:cdk:path: performance-metrics/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  PerformanceApiEndpoint283CEB44:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: PerformanceApi49E4F80B
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: PerformanceApiDeploymentStageawsunknownaccountunknownregionAA2390C8
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store.
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 4 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

